---
parent: 'common/test_cases/origin_installed_release.yml'
overrides:
  sync_repos:
    - name: "origin-aggregated-logging"
extensions:
  actions:
    - type: "script"
      title: "install origin-aggregated-logging"
      repository: "aos-cd-jobs"
      script: |-
        ansible-playbook -vv --become               \
                         --become-user root         \
                         --connection local         \
                         --inventory sjb/inventory/ \
                         -e deployment_type=origin  \
                         -e openshift_logging_image_prefix="openshift/origin-" \
                         -e openshift_hosted_logging_hostname="kibana.127.0.0.1.xip.io"           \
                         -e openshift_logging_master_public_url="https://localhost:8443"          \
                         -e openshift_master_logging_public_url="https://kibana.127.0.0.1.xip.io" \
                         /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/openshift-logging.yml \
                         --skip-tags=update_master_config
    - type: "script"
      title: "run logging tests"
      repository: "origin-aggregated-logging"
      script: |-
        export KUBECONFIG=/etc/origin/master/admin.kubeconfig
        export TEST_ONLY=true
        export ENABLE_OPS_CLUSTER=true
        export USE_LOCAL_SOURCE=true
        export OS_O_A_L_DIR="$( pwd )"
        export OS_ROOT="$( realpath ./../origin )"
        hack/testing/check-EFK-running.sh
        hack/testing/check-logs.sh
